### ISSUE TITLE
BUG: Catalog search "copies" icon always green

### ISSUE THREAD

**Issue by shiv379** [Librarika/Issues#303]
I'm assuming the icon next to the actions column in a catalog search should shade based on whether there is a copy currently in the library or not, however currently it is always green.

**Comment by rayhan** [comment]
Fixed :+1:

**Comment by shiv379** [comment]
Just had a look on our library and this bug still seems to be present

**Comment by rayhan** [comment]
Which page do you mean? Dashboard -> Catalog or OPAC catalog search page?

**Comment by shiv379** [comment]
Dashboard page...
https://XXX.librarika.com/media

**Comment by rayhan** [comment]
Can you double check and show me a screenshot if possible, I checked all books in your library and none has 0 copies.

**Comment by shiv379** [comment]
Ah maybe I am misunderstanding the functionality! I had assumed it showed the number of copies available (as in, number of copies on the database that are not currently checked out). Is that not the case?

**Comment by rayhan** [comment]
Not, it is not the case. It shows total number of copies only, but you have raised a very good point.

**Comment by shiv379** [comment]
Ah that would be why! As a Librarian it would be more useful to show the number of copies currently in Stock (not on loan) as we often have queries of that nature and it would save having to go into the details page. I would like to suggest this part shows the current number available :-)
Going forward maybe you could change this to show a number like 2/3 in the box - meaning there are three copies in the library of which two are currently on the shelves.

**Comment by rayhan** [comment]
Yes, right.
